site_name: Surf
repo_url: https://github.com/headzoo/surf
site_description: Stateful programmatic web browsing in Go.
site_author: Sean Hickey
theme: readthedocs
pages:
- [index.md, Home]
- [quick_start.md, User Guide, Quick Start]
- [settings.md, User Guide, Settings]
- [user_agents.md, User Guide, User Agents]
- [api/packages/surf.md, Packages, surf]
- [api/packages/browser.md, Packages, browser]
- [api/packages/agent.md, Packages, agent]
- [api/packages/jar.md, Packages, jar]
- [api/packages/util.md, Packages, util]
- [about/credits.md, About, Credits]