site_name: Surf
repo_url: https://github.com/headzoo/surf
site_description: Stateful programmatic web browsing in Go.
site_author: Sean Hickey
theme: readthedocs
pages:
- [index.md, Home]
- [overview.md, Overview]
- [settings.md, Settings Overview]
- [user_agents.md, User Agent Settings]
- [downloading.md, Downloading Pages]
- [credits.md, Credits]
- [api/surf.md, API, surf]
- [api/browser.md, API, browser]
- [api/agent.md, API, agent]
- [api/jar.md, API, jar]
- [api/util.md, API, util]