site_name: Surf
repo_url: https://github.com/headzoo/surf
site_description: Stateful programmatic web browsing in Go.
site_author: Sean Hickey
theme: readthedocs
pages:
- [index.md, Home]
- [downloading.md, Downloading Pages]
- [settings.md, Settings Overview]
- [user_agents.md, User Agent Settings]
- [credits.md, Credits]